name: athenas
description: "A drone control application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # BLoC for state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # WebSocket for real-time communication with drone
  socket_io_client: ^2.0.3+1
  
  # HTTP clients for API requests
  dio: ^5.3.0
  http: ^1.1.0
  
  # UI components
  material_design_icons_flutter: ^7.0.7296
  
  # Joystick control
  flutter_joystick: ^0.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
