name: CI - Spring Boot Build and Health Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Load environment variables
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Run Spring Boot (background)
        run: |
          export $(grep -v '^#' .env | xargs)
          nohup ./mvnw spring-boot:run &
          sleep 20

      - name: Ping server
        run: curl --fail http://localhost:8080 || exit 1
