name: CI - Spring Boot Build and Health Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: jdbc:postgresql://localhost:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Maven wrapper
        run: chmod +x mvnw
        working-directory: src/backend

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        working-directory: src/backend

      - name: Run Spring Boot and wait for server
        run: |
          ./mvnw spring-boot:run &
          for i in {1..30}; do
            sleep 2
            if curl --fail http://localhost:8080; then
              echo "Server is up"
              exit 0
            fi
          done
          echo "Server failed to start"
          exit 1
        working-directory: src/backend
